bump_version: null
lint:
  files_exist:
  - conf/igenomes.config
  - conf/igenomes_ignored.config
  - conf/igenomes.config
  - conf/igenomes_ignored.config
  - CODE_OF_CONDUCT.md
  - assets/nf-core-nanotax_logo_light.png
  - docs/images/nf-core-nanotax_logo_light.png
  - docs/images/nf-core-nanotax_logo_dark.png
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/workflows/awstest.yml
  - .github/workflows/awsfulltest.yml
  files_unchanged:
  - CODE_OF_CONDUCT.md
  - assets/nf-core-nanotax_logo_light.png
  - docs/images/nf-core-nanotax_logo_light.png
  - docs/images/nf-core-nanotax_logo_dark.png
  - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config:
  - report_comment
  nextflow_config:
  - manifest.name
  - manifest.homePage
  - validation.help.beforeText
  - validation.help.afterText
  - validation.summary.beforeText
  - validation.summary.afterText
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: JacquelineAld
  description: A pipeline for the characterization of microbial communities with Nanopore
  force: true
  is_nfcore: false
  name: NanoTax
  org: catg
  outdir: .
  skip_features:
  - igenomes
  - gitpod
  version: 1.0.0dev
update: null
